### ISSUE TITLE
v1.0.1 does not display map correctly

### ISSUE THREAD

**Issue by za267** [thomasrudin-mt/mapserver#17]
Hi there, I've just switched to v1.0.1 this morning and while the program feels stable and generates images, it does not display any images when navigating to the site.  Just a grayish background.  All the leaflet artifacts show up properly though, so I wonder if its an issue with reading the images.

I've also tried by removing the v1.0.0 generated tile folder and sqlite file... The new tile folder contained newly generated images, but still the website only displayed a grayish background with no images at any zoom level.

**Comment by thomasrudin** [comment]
That was my fault, i did not test it properly with multiple layers.
Will do a release with the bugfixes for postgres...
