### ISSUE TITLE
How does it increment the map?

### ISSUE THREAD

**Issue by za267** [thomasrudin-mt/mapserver#20]
Hi, This is not a problem but a question regarding the internal functionality.  I've finished with the initial rendering of my map and now its doing incremental rendering.  However, its taking a long time to do the incremental and I don't really see any live changes.

NOTE: I had to stop the 'initial rendering' for a few days due to a bug which caused the mapper to crash.  I'm on the latest development branch as of today and its working well right now.

This got me thinking and I started looking at the mtime column on the database.  If that keeps track of the changed and updated blocks, how does it know when it last got rendered on the map?  Shouldn't there be a 'dirty' field which keeps track?

UPDATE: Starting to update live now.  :)

**Comment by thomasrudin** [comment]
This should clarify the update a bit: https://github.com/thomasrudin-mt/mapserver/blob/master/doc/incrementalrendering.md

There may be bugs in the current master branch, but they should get fixed as i try to render my main map (https://test.pandorabox.io/map)

Also: for big maps the sqlite db (for the mapobjects) has perf issues, a postgres alternative should work better (#19)

**Comment by za267** [comment]
Well, thanks for the new docs - I just saw the commit.  Awesome!  :)
